---
name: 'open-subjects'

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: "open-subjects:linter"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Super-Linter.
        uses: github/super-linter@v3.14.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  mkdocs:
    name: "open-subjects:mkdocs"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Setup Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install mkdocs dependencies.
        run: pip install -r subjects/requirements.txt

      - name: Deploy mkdocs documentation
        run: mkdocs gh-deploy --force
        if: ${{ github.event_name == 'push' }}
